### PR TITLE
Custom Messages

### PR DESCRIPTION
**Pull request by johnmanko**
Allows users to use custom messages and built-in parameter tokens.
Could probably be extended to also allow for custom parameters.

### CODE REVIEW

**Comment by johnmanko** [comment]
@geraintluff Just wondering if you had a chance to look at this PR.

**Comment by geraintluff** [comment]
This is a cool feature - however, it introduces a custom tv4-specific schema keyword (`messages`), which is something I've so far avoided.

What is your use-case, and is it possible to summarise the requirements in `description` instead? (e.g. `{"pattern": ..., "description": "Human-friendly text that makes more sense than a regex"}`)

**Comment by johnmanko** [comment]
To answer the "pattern" option first, that defeats the benefit of using built-in types.  

The use case is one in which I want to display user friendly messages.

Regarding "messages" not being part of the spec, I have to say that the spec looks fairly incomplete.  :)  I completely understand your point, but all spec evolution comes from outside influence.  I've spent many years in the Java EE world, and I can atest from personal experience that all of the modern EE specs have derived themselves from outside Java Community Process.  In fact, it's been the success of real world independent frameworks and open source projects that have driven the JCP, to the point that the spec teams are now headed by those who developed those conventions outside of the JSP.  

The JSON Schema is currently in v4 draft, which means that there is still time to propose additions, such as "messages".  The validation is already part of the schema, so why not custom messages to go with it? Maybe we can contact the RFC authors directly and point them to this thread?

http://tools.ietf.org/html/draft-fge-json-schema-validation-00

**Comment by johnmanko** [comment]
@geraintluff I filed this with the spec team.  Hopefully they accept it: https://github.com/json-schema/json-schema/issues/183

**Pull request closed without merging**
