### PR TITLE
add TypeScript decl file

### PR DESCRIPTION
**Pull request by psnider**
I would like to add an updated TypeScript declaration file to your module,
along with a test,
so that it will be easier to keep it in sync with the library.

I chose putting it in the typings/tv4 directory, along with a test file of the form that's expected by DefinitelyTyped.

See the issue I filed for more info: https://github.com/geraintluff/tv4/issues/213

### CODE REVIEW

**Comment by psnider** [comment]
You may want to wait to merge this until I receive feedback from the DefinitelyTyped folks,
just in case they want me to make any further changes...

**Comment by psnider** [comment]
This was just accepted by DefinitelyTyped!
Please go ahead and commit this now.

**Comment by geraintluff** [comment]
I'm getting an error:

> Running "exec:testTypeScriptDecls" (exec) task
> \>> /bin/sh: tsc: command not found
> \>> Exited with code: 127.
> Warning: Task "exec:testTypeScriptDecls" failed. Use --force to continue.

What am I missing?

Also, I'm still unclear on what additional responsibilities this PR would mean.  If I change the API, do I have to find a TypeScript person before I can release?  What's the difference between the definition here and what's in DefinitelyTyped?  Why does it need something in both packages?

Sorry, I've not looked at TypeScript very closely, so these questions might be a bit obvious.

**Comment by psnider** [comment]
For the error: try running ```npm install typescript```, I already added it to package.json's devDependencies.

For updating the TypeScript declarations file: you can either ask me, or ask for help from the community by creating an issue on https://github.com/borisyankov/DefinitelyTyped/issues
If you don't get a response, you may want to message the curators directly.
@vvakame appears to be most active.
But perhaps if your API changes are minor, you may feel like you can make them yourself.

For API changes, you can publish the API as you like, soliciting for help before or after.
Before is preferable, but many packages have slightly out-of-date declarations files.
I recommend that you ask for help first, and if it looks like it will be provided quickly, wait.
But if you don't get a response, or it looks like it will take a while, go ahead and release.
Someone who needs the update will make the changes.

I'll be glad to help you whenever I can...

**Comment by psnider** [comment]
Also, the tests run for grunt target *exec:testTypeScriptDecls* may fail if the current APIs change.
They will not catch any additional APIs, and should be extended in that case.
The basic tests are usually taken from the examples in a]the README file.

**Pull request closed without merging**
