### PR TITLE
A simple command line tool for tv4

### PR DESCRIPTION
**Pull request by steenk**
I made a command line tool for my own need. It would be nice if it can be added to the master.
/Steen

### CODE REVIEW

**Comment by kwent** [comment]
:+1: +1

**Comment by tamlyn** [comment]
+2 Works well. 

If this doesn't fit with the tv4 project vision then maybe it could be split into a separate project.

**Comment by geraintluff** [comment]
I agree - I like this tool, but it adds a dependency on `nopt` which isn't necessary for most use cases (including Browserify/etc.).

I think having this as a separate package (e.g. `tv4-cmd`) would be good.  A tool like this sounds neat, so if you published it I'd definitely link to it from the README.

**Comment by steenk** [comment]
geraintluff,
I agree with you on unnecessary dependencies, and I think making an optional package `tv4-cmd` is a good solution.

**Comment by geraintluff** [comment]
OK, cool.  So, if you're OK making a `tv4-cmd` module, that'd be great.  If you let me know when it's published, I can link to it. :)

**Comment by steenk** [comment]
I made a quick project of it here: [](https://www.npmjs.com/package/tv4-cmd).

**Comment by geraintluff** [comment]
Nice!

Closing this PR - I'll link to it from the README instead.

**Pull request closed without merging**
