### PR TITLE
Recursive/deep references

### PR DESCRIPTION
**Pull request by israelshirk**
Helps with complicated schema like https://gist.github.com/israelshirk/0fdc158e70d82f6ba90f#file-in-schema-json

### CODE REVIEW

**Comment by geraintluff** [comment]
Hi - what was the actual error you were seeing?

A test case would be ideal, but otherwise some example code that demonstrates would be great.

**Comment by israelshirk** [comment]
So I'm defining the entire [DML and DDL reference](http://www.orafaq.com/faq/what_are_the_difference_between_ddl_dml_and_dcl_commands) for both backend and frontend using JSON hyper-schema, along with [PRMD](https://github.com/interagent/prmd) helping to simplify de-duplication of relational information.  In that context, references get pretty involved and can nest to several layers pretty quickly; but the deduplication of types, definitions, etc makes a big difference in maintainability and coding velocity in that you don't have to spend time tracking changes/etc - just use a reference and it propagates all the way through your DB backend schema schanges and frontend views - they're all built from the schema as a single source of truth, and the representations of any object are just manifestations that the framework generates from JSON hyper-schema.

## Quick deep dive
_pardon the work in construction if you look at the gists_

### Data Definitions
There's a definitions file which contains generic data types, (will contain) relational object definitions, etc: [definitions.json](https://gist.githubusercontent.com/israelshirk/c6742778ab5c3e1c14ec/raw/definitions.json)

### Model definitions
#### User model/RPC hyper-schema
We define a user in [model/user.json](https://gist.githubusercontent.com/israelshirk/c6742778ab5c3e1c14ec/raw/model_user.json); users belong to groups in a many-to-many relationship through the group members model; and there are various actions defined on the user which will involve lookups to groups through actions defined in the hyper-schema links (which reference the group membership model's lookup methods).

#### Group model/RPC hyper-schema
We define a group in [model/group.json](https://gist.githubusercontent.com/israelshirk/c6742778ab5c3e1c14ec/raw/model_group.json); it (will have) various RPC methods defined for administration of the group, looking up a group's members, adding/removing group members, etc - which are actually defined in the group_members hyper-schema but referenced as actions on the group's hyper-schema definition.

#### Group members model
We define a group members model in [model/group_member.json](https://gist.githubusercontent.com/israelshirk/c6742778ab5c3e1c14ec/raw/model_group_member.json); it relates users to the groups they belong to (and external stuff like roles in the group that we don't deal with in this writeup).  This hyper-schema defines actions like creating/adding/deleting the relationships between users and groups.

### Bringing definitions/models together
[PRMD](https://github.com/interagent/prmd) is used to combine definitions and model definition files into a single downloadable JSON asset; however for PRMD or a similar tool to resolve all the references involved would result in either huge outputs or recursive/impossible-to-follow references since users, groups, and group members end up self-referencing.

## TV4 as a solution for part of the problem
TV4 is used for lookup and validation of models on the Javascript frontend; if we inform it of how to recurse through references to the single points of truth (type definitions and link references) for object we're attempting to access, we end up with a nice, compact, maintainable set of JSON hyper-schema for types, models, and RPCs which we can then extract, manipulate, and validate with minimal effort.

### Validation
For example, if we want to create and validate a form to create a user, our original JSON hyper schema keeps a nice small footprint:
```json
    {
      "description": "Create a new user.",
      "href": "/user/",
      "method": "POST",
      "rel": "create",
      "schema": {
        "properties": {
          "first_name": { "$ref": "/user#/definitions/first_name" },
          "last_name": { "$ref": "/user#/definitions/last_name" },
          "slug": { "$ref": "/user#/definitions/slug" },
          "password": { "$ref": "/user#/definitions/password" },
          "spam": { "$ref": "/user#/definitions/spam" },
          "two_factor_token": { "$ref": "/user#/definitions/two_factor_token" },
          "email": { "$ref": "/user#/definitions/email" }
        },
        "type": "object"
      },
      "title": "Create"
    }
```

I'm ignoring PRMD's translation and the framework's reading of the model's links somewhat, but if we wanted to validate against the link's schema we'd do:
```javascript
user.first_name=...;
user.last_name=...;
user.validate()
```

The user model becomes self-aware and calls tv4 with:
```javascript
tv4.validateAll({"first_name": "Johnny", ...}, "http://api.yeti-support.com/schema.json#/models/user/links/0/schema/");
```

tv4 then transparently traverses a couple layers of schema references to the source of truth for the types in question:
`user.json#/definitions/first_name` -> `definitions.json#/definitions/first_name` -> `definitions.json#/definitions/name`, and ends up with a meaningful result.

### Model definition lookups/etc
Since we've already created the logic above for traversing schema references, we use it to resolve references into meaningful things for creating meaningful models to provide fluent, live-validating models.  This is pretty much just a bonus and outside the scope of tv4, but it de-duplicates all the code I'd have to do to actually get to validating things in the first place if I can just define models using JSON [hyper-] schema in the first place.

## Ok that's way too much typing and you quit reading a while ago
Adding the ability to tv4 to look up several layers of schema references makes it super super useful for creating frameworks which require minimal effort to do really really cool things.

**Comment by israelshirk** [comment]
Also, there were no specific errors - schema references past the first level just weren't getting populated.  I think there's somewhat better ways to handle the references here (translating URL references to JS objects simplifies traversal quite a bit and avoids having to deal with cyclical references almost entirely) - I just wasn't sure how far I should go with it.  There are a couple simple test cases in the PR - basically A references B, B references C, ...

**Comment by israelshirk** [comment]
This needed a minor rewrite on lookups to work efficiently.  Closing here; may be a little while before I have a chance to clean up and PR the other side of things.

**Pull request closed without merging**
